version: 2
updates:
  - package-ecosystem: swift
    directory: /ios
    schedule:
      interval: weekly
      day: monday
    groups:
      swift-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
